// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base_message.proto

package com.asm.zim.common.proto;

public final class BaseMessage {
  private BaseMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageFileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.asm.zim.common.proto.MessageFile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string messageId = 2;</code>
     */
    String getMessageId();
    /**
     * <code>string messageId = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <code>string fileName = 3;</code>
     */
    String getFileName();
    /**
     * <code>string fileName = 3;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>int64 size = 4;</code>
     */
    long getSize();

    /**
     * <code>string suffix = 5;</code>
     */
    String getSuffix();
    /**
     * <code>string suffix = 5;</code>
     */
    com.google.protobuf.ByteString
        getSuffixBytes();

    /**
     * <code>string url = 6;</code>
     */
    String getUrl();
    /**
     * <code>string url = 6;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>int64 createTime = 7;</code>
     */
    long getCreateTime();
  }
  /**
   * Protobuf type {@code com.asm.zim.common.proto.MessageFile}
   */
  public  static final class MessageFile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.asm.zim.common.proto.MessageFile)
      MessageFileOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageFile.newBuilder() to construct.
    private MessageFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageFile() {
      id_ = "";
      messageId_ = "";
      fileName_ = "";
      size_ = 0L;
      suffix_ = "";
      url_ = "";
      createTime_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageFile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              messageId_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 32: {

              size_ = input.readInt64();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              suffix_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 56: {

              createTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseMessage.internal_static_com_asm_zim_common_proto_MessageFile_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseMessage.internal_static_com_asm_zim_common_proto_MessageFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageFile.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGEID_FIELD_NUMBER = 2;
    private volatile Object messageId_;
    /**
     * <code>string messageId = 2;</code>
     */
    public String getMessageId() {
      Object ref = messageId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      }
    }
    /**
     * <code>string messageId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      Object ref = messageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILENAME_FIELD_NUMBER = 3;
    private volatile Object fileName_;
    /**
     * <code>string fileName = 3;</code>
     */
    public String getFileName() {
      Object ref = fileName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string fileName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIZE_FIELD_NUMBER = 4;
    private long size_;
    /**
     * <code>int64 size = 4;</code>
     */
    public long getSize() {
      return size_;
    }

    public static final int SUFFIX_FIELD_NUMBER = 5;
    private volatile Object suffix_;
    /**
     * <code>string suffix = 5;</code>
     */
    public String getSuffix() {
      Object ref = suffix_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        suffix_ = s;
        return s;
      }
    }
    /**
     * <code>string suffix = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSuffixBytes() {
      Object ref = suffix_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        suffix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URL_FIELD_NUMBER = 6;
    private volatile Object url_;
    /**
     * <code>string url = 6;</code>
     */
    public String getUrl() {
      Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>string url = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 7;
    private long createTime_;
    /**
     * <code>int64 createTime = 7;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, messageId_);
      }
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fileName_);
      }
      if (size_ != 0L) {
        output.writeInt64(4, size_);
      }
      if (!getSuffixBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, suffix_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, url_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(7, createTime_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, messageId_);
      }
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fileName_);
      }
      if (size_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, size_);
      }
      if (!getSuffixBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, suffix_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, url_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, createTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessageFile)) {
        return super.equals(obj);
      }
      MessageFile other = (MessageFile) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getMessageId()
          .equals(other.getMessageId());
      result = result && getFileName()
          .equals(other.getFileName());
      result = result && (getSize()
          == other.getSize());
      result = result && getSuffix()
          .equals(other.getSuffix());
      result = result && getUrl()
          .equals(other.getUrl());
      result = result && (getCreateTime()
          == other.getCreateTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSize());
      hash = (37 * hash) + SUFFIX_FIELD_NUMBER;
      hash = (53 * hash) + getSuffix().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessageFile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageFile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessageFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessageFile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.asm.zim.common.proto.MessageFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.asm.zim.common.proto.MessageFile)
        MessageFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseMessage.internal_static_com_asm_zim_common_proto_MessageFile_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseMessage.internal_static_com_asm_zim_common_proto_MessageFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageFile.class, Builder.class);
      }

      // Construct using com.asm.zim.common.proto.BaseMessage.MessageFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = "";

        messageId_ = "";

        fileName_ = "";

        size_ = 0L;

        suffix_ = "";

        url_ = "";

        createTime_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseMessage.internal_static_com_asm_zim_common_proto_MessageFile_descriptor;
      }

      @Override
      public MessageFile getDefaultInstanceForType() {
        return MessageFile.getDefaultInstance();
      }

      @Override
      public MessageFile build() {
        MessageFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MessageFile buildPartial() {
        MessageFile result = new MessageFile(this);
        result.id_ = id_;
        result.messageId_ = messageId_;
        result.fileName_ = fileName_;
        result.size_ = size_;
        result.suffix_ = suffix_;
        result.url_ = url_;
        result.createTime_ = createTime_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageFile) {
          return mergeFrom((MessageFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageFile other) {
        if (other == MessageFile.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getMessageId().isEmpty()) {
          messageId_ = other.messageId_;
          onChanged();
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.getSize() != 0L) {
          setSize(other.getSize());
        }
        if (!other.getSuffix().isEmpty()) {
          suffix_ = other.suffix_;
          onChanged();
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessageFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessageFile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private Object messageId_ = "";
      /**
       * <code>string messageId = 2;</code>
       */
      public String getMessageId() {
        Object ref = messageId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          messageId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string messageId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageId = 2;</code>
       */
      public Builder setMessageId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string messageId = 2;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>string messageId = 2;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageId_ = value;
        onChanged();
        return this;
      }

      private Object fileName_ = "";
      /**
       * <code>string fileName = 3;</code>
       */
      public String getFileName() {
        Object ref = fileName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string fileName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileName = 3;</code>
       */
      public Builder setFileName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 3;</code>
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 3;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private long size_ ;
      /**
       * <code>int64 size = 4;</code>
       */
      public long getSize() {
        return size_;
      }
      /**
       * <code>int64 size = 4;</code>
       */
      public Builder setSize(long value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 size = 4;</code>
       */
      public Builder clearSize() {
        
        size_ = 0L;
        onChanged();
        return this;
      }

      private Object suffix_ = "";
      /**
       * <code>string suffix = 5;</code>
       */
      public String getSuffix() {
        Object ref = suffix_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          suffix_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string suffix = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSuffixBytes() {
        Object ref = suffix_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          suffix_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string suffix = 5;</code>
       */
      public Builder setSuffix(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        suffix_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string suffix = 5;</code>
       */
      public Builder clearSuffix() {
        
        suffix_ = getDefaultInstance().getSuffix();
        onChanged();
        return this;
      }
      /**
       * <code>string suffix = 5;</code>
       */
      public Builder setSuffixBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        suffix_ = value;
        onChanged();
        return this;
      }

      private Object url_ = "";
      /**
       * <code>string url = 6;</code>
       */
      public String getUrl() {
        Object ref = url_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string url = 6;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string url = 6;</code>
       */
      public Builder setUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string url = 6;</code>
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string url = 6;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>int64 createTime = 7;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>int64 createTime = 7;</code>
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 createTime = 7;</code>
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.asm.zim.common.proto.MessageFile)
    }

    // @@protoc_insertion_point(class_scope:com.asm.zim.common.proto.MessageFile)
    private static final MessageFile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageFile();
    }

    public static MessageFile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageFile>
        PARSER = new com.google.protobuf.AbstractParser<MessageFile>() {
      @Override
      public MessageFile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageFile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageFile> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessageFile> getParserForType() {
      return PARSER;
    }

    @Override
    public MessageFile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.asm.zim.common.proto.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     *系统消息生效 系统功能码
     * </pre>
     *
     * <code>int32 code = 2;</code>
     */
    int getCode();

    /**
     * <code>string fromId = 3;</code>
     */
    String getFromId();
    /**
     * <code>string fromId = 3;</code>
     */
    com.google.protobuf.ByteString
        getFromIdBytes();

    /**
     * <code>string toId = 4;</code>
     */
    String getToId();
    /**
     * <code>string toId = 4;</code>
     */
    com.google.protobuf.ByteString
        getToIdBytes();

    /**
     * <code>string content = 5;</code>
     */
    String getContent();
    /**
     * <code>string content = 5;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>int64 sendTime = 6;</code>
     */
    long getSendTime();

    /**
     * <pre>
     *1：系统消息  2：普通消息
     * </pre>
     *
     * <code>int32 messageType = 7;</code>
     */
    int getMessageType();

    /**
     * <pre>
     *消息类别 1 普通文本 2 文件
     * </pre>
     *
     * <code>int32 messageCategory = 8;</code>
     */
    int getMessageCategory();

    /**
     * <pre>
     *聊天类型 1.群聊 2.私聊 3.消息推送
     * </pre>
     *
     * <code>int32 chatType = 9;</code>
     */
    int getChatType();

    /**
     * <pre>
     *终端类型
     * </pre>
     *
     * <code>int32 terminalType = 10;</code>
     */
    int getTerminalType();

    /**
     * <pre>
     *协议
     * </pre>
     *
     * <code>string protocol = 11;</code>
     */
    String getProtocol();
    /**
     * <pre>
     *协议
     * </pre>
     *
     * <code>string protocol = 11;</code>
     */
    com.google.protobuf.ByteString
        getProtocolBytes();

    /**
     * <code>string token = 12;</code>
     */
    String getToken();
    /**
     * <code>string token = 12;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <pre>
     *其他属性
     * </pre>
     *
     * <code>string data = 13;</code>
     */
    String getData();
    /**
     * <pre>
     *其他属性
     * </pre>
     *
     * <code>string data = 13;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>.com.asm.zim.common.proto.MessageFile messageFile = 14;</code>
     */
    boolean hasMessageFile();
    /**
     * <code>.com.asm.zim.common.proto.MessageFile messageFile = 14;</code>
     */
    MessageFile getMessageFile();
    /**
     * <code>.com.asm.zim.common.proto.MessageFile messageFile = 14;</code>
     */
    MessageFileOrBuilder getMessageFileOrBuilder();
  }
  /**
   * Protobuf type {@code com.asm.zim.common.proto.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.asm.zim.common.proto.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      id_ = "";
      code_ = 0;
      fromId_ = "";
      toId_ = "";
      content_ = "";
      sendTime_ = 0L;
      messageType_ = 0;
      messageCategory_ = 0;
      chatType_ = 0;
      terminalType_ = 0;
      protocol_ = "";
      token_ = "";
      data_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              code_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              fromId_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              toId_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 48: {

              sendTime_ = input.readInt64();
              break;
            }
            case 56: {

              messageType_ = input.readInt32();
              break;
            }
            case 64: {

              messageCategory_ = input.readInt32();
              break;
            }
            case 72: {

              chatType_ = input.readInt32();
              break;
            }
            case 80: {

              terminalType_ = input.readInt32();
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              protocol_ = s;
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 106: {
              String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 114: {
              MessageFile.Builder subBuilder = null;
              if (messageFile_ != null) {
                subBuilder = messageFile_.toBuilder();
              }
              messageFile_ = input.readMessage(MessageFile.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(messageFile_);
                messageFile_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseMessage.internal_static_com_asm_zim_common_proto_Message_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseMessage.internal_static_com_asm_zim_common_proto_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <pre>
     *系统消息生效 系统功能码
     * </pre>
     *
     * <code>int32 code = 2;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int FROMID_FIELD_NUMBER = 3;
    private volatile Object fromId_;
    /**
     * <code>string fromId = 3;</code>
     */
    public String getFromId() {
      Object ref = fromId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fromId_ = s;
        return s;
      }
    }
    /**
     * <code>string fromId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      Object ref = fromId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOID_FIELD_NUMBER = 4;
    private volatile Object toId_;
    /**
     * <code>string toId = 4;</code>
     */
    public String getToId() {
      Object ref = toId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        toId_ = s;
        return s;
      }
    }
    /**
     * <code>string toId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getToIdBytes() {
      Object ref = toId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        toId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 5;
    private volatile Object content_;
    /**
     * <code>string content = 5;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 5;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTIME_FIELD_NUMBER = 6;
    private long sendTime_;
    /**
     * <code>int64 sendTime = 6;</code>
     */
    public long getSendTime() {
      return sendTime_;
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 7;
    private int messageType_;
    /**
     * <pre>
     *1：系统消息  2：普通消息
     * </pre>
     *
     * <code>int32 messageType = 7;</code>
     */
    public int getMessageType() {
      return messageType_;
    }

    public static final int MESSAGECATEGORY_FIELD_NUMBER = 8;
    private int messageCategory_;
    /**
     * <pre>
     *消息类别 1 普通文本 2 文件
     * </pre>
     *
     * <code>int32 messageCategory = 8;</code>
     */
    public int getMessageCategory() {
      return messageCategory_;
    }

    public static final int CHATTYPE_FIELD_NUMBER = 9;
    private int chatType_;
    /**
     * <pre>
     *聊天类型 1.群聊 2.私聊 3.消息推送
     * </pre>
     *
     * <code>int32 chatType = 9;</code>
     */
    public int getChatType() {
      return chatType_;
    }

    public static final int TERMINALTYPE_FIELD_NUMBER = 10;
    private int terminalType_;
    /**
     * <pre>
     *终端类型
     * </pre>
     *
     * <code>int32 terminalType = 10;</code>
     */
    public int getTerminalType() {
      return terminalType_;
    }

    public static final int PROTOCOL_FIELD_NUMBER = 11;
    private volatile Object protocol_;
    /**
     * <pre>
     *协议
     * </pre>
     *
     * <code>string protocol = 11;</code>
     */
    public String getProtocol() {
      Object ref = protocol_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        protocol_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *协议
     * </pre>
     *
     * <code>string protocol = 11;</code>
     */
    public com.google.protobuf.ByteString
        getProtocolBytes() {
      Object ref = protocol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        protocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 12;
    private volatile Object token_;
    /**
     * <code>string token = 12;</code>
     */
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 12;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 13;
    private volatile Object data_;
    /**
     * <pre>
     *其他属性
     * </pre>
     *
     * <code>string data = 13;</code>
     */
    public String getData() {
      Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *其他属性
     * </pre>
     *
     * <code>string data = 13;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGEFILE_FIELD_NUMBER = 14;
    private MessageFile messageFile_;
    /**
     * <code>.com.asm.zim.common.proto.MessageFile messageFile = 14;</code>
     */
    public boolean hasMessageFile() {
      return messageFile_ != null;
    }
    /**
     * <code>.com.asm.zim.common.proto.MessageFile messageFile = 14;</code>
     */
    public MessageFile getMessageFile() {
      return messageFile_ == null ? MessageFile.getDefaultInstance() : messageFile_;
    }
    /**
     * <code>.com.asm.zim.common.proto.MessageFile messageFile = 14;</code>
     */
    public MessageFileOrBuilder getMessageFileOrBuilder() {
      return getMessageFile();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (code_ != 0) {
        output.writeInt32(2, code_);
      }
      if (!getFromIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fromId_);
      }
      if (!getToIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, toId_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, content_);
      }
      if (sendTime_ != 0L) {
        output.writeInt64(6, sendTime_);
      }
      if (messageType_ != 0) {
        output.writeInt32(7, messageType_);
      }
      if (messageCategory_ != 0) {
        output.writeInt32(8, messageCategory_);
      }
      if (chatType_ != 0) {
        output.writeInt32(9, chatType_);
      }
      if (terminalType_ != 0) {
        output.writeInt32(10, terminalType_);
      }
      if (!getProtocolBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, protocol_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, token_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, data_);
      }
      if (messageFile_ != null) {
        output.writeMessage(14, getMessageFile());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, code_);
      }
      if (!getFromIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fromId_);
      }
      if (!getToIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, toId_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, content_);
      }
      if (sendTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, sendTime_);
      }
      if (messageType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, messageType_);
      }
      if (messageCategory_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, messageCategory_);
      }
      if (chatType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, chatType_);
      }
      if (terminalType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, terminalType_);
      }
      if (!getProtocolBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, protocol_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, token_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, data_);
      }
      if (messageFile_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, getMessageFile());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Message)) {
        return super.equals(obj);
      }
      Message other = (Message) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && (getCode()
          == other.getCode());
      result = result && getFromId()
          .equals(other.getFromId());
      result = result && getToId()
          .equals(other.getToId());
      result = result && getContent()
          .equals(other.getContent());
      result = result && (getSendTime()
          == other.getSendTime());
      result = result && (getMessageType()
          == other.getMessageType());
      result = result && (getMessageCategory()
          == other.getMessageCategory());
      result = result && (getChatType()
          == other.getChatType());
      result = result && (getTerminalType()
          == other.getTerminalType());
      result = result && getProtocol()
          .equals(other.getProtocol());
      result = result && getToken()
          .equals(other.getToken());
      result = result && getData()
          .equals(other.getData());
      result = result && (hasMessageFile() == other.hasMessageFile());
      if (hasMessageFile()) {
        result = result && getMessageFile()
            .equals(other.getMessageFile());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + FROMID_FIELD_NUMBER;
      hash = (53 * hash) + getFromId().hashCode();
      hash = (37 * hash) + TOID_FIELD_NUMBER;
      hash = (53 * hash) + getToId().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendTime());
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType();
      hash = (37 * hash) + MESSAGECATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getMessageCategory();
      hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getChatType();
      hash = (37 * hash) + TERMINALTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getTerminalType();
      hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
      hash = (53 * hash) + getProtocol().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      if (hasMessageFile()) {
        hash = (37 * hash) + MESSAGEFILE_FIELD_NUMBER;
        hash = (53 * hash) + getMessageFile().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.asm.zim.common.proto.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.asm.zim.common.proto.Message)
        MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseMessage.internal_static_com_asm_zim_common_proto_Message_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseMessage.internal_static_com_asm_zim_common_proto_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.class, Builder.class);
      }

      // Construct using com.asm.zim.common.proto.BaseMessage.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = "";

        code_ = 0;

        fromId_ = "";

        toId_ = "";

        content_ = "";

        sendTime_ = 0L;

        messageType_ = 0;

        messageCategory_ = 0;

        chatType_ = 0;

        terminalType_ = 0;

        protocol_ = "";

        token_ = "";

        data_ = "";

        if (messageFileBuilder_ == null) {
          messageFile_ = null;
        } else {
          messageFile_ = null;
          messageFileBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseMessage.internal_static_com_asm_zim_common_proto_Message_descriptor;
      }

      @Override
      public Message getDefaultInstanceForType() {
        return Message.getDefaultInstance();
      }

      @Override
      public Message build() {
        Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Message buildPartial() {
        Message result = new Message(this);
        result.id_ = id_;
        result.code_ = code_;
        result.fromId_ = fromId_;
        result.toId_ = toId_;
        result.content_ = content_;
        result.sendTime_ = sendTime_;
        result.messageType_ = messageType_;
        result.messageCategory_ = messageCategory_;
        result.chatType_ = chatType_;
        result.terminalType_ = terminalType_;
        result.protocol_ = protocol_;
        result.token_ = token_;
        result.data_ = data_;
        if (messageFileBuilder_ == null) {
          result.messageFile_ = messageFile_;
        } else {
          result.messageFile_ = messageFileBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message) {
          return mergeFrom((Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message other) {
        if (other == Message.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getFromId().isEmpty()) {
          fromId_ = other.fromId_;
          onChanged();
        }
        if (!other.getToId().isEmpty()) {
          toId_ = other.toId_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getSendTime() != 0L) {
          setSendTime(other.getSendTime());
        }
        if (other.getMessageType() != 0) {
          setMessageType(other.getMessageType());
        }
        if (other.getMessageCategory() != 0) {
          setMessageCategory(other.getMessageCategory());
        }
        if (other.getChatType() != 0) {
          setChatType(other.getChatType());
        }
        if (other.getTerminalType() != 0) {
          setTerminalType(other.getTerminalType());
        }
        if (!other.getProtocol().isEmpty()) {
          protocol_ = other.protocol_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (other.hasMessageFile()) {
          mergeMessageFile(other.getMessageFile());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       *系统消息生效 系统功能码
       * </pre>
       *
       * <code>int32 code = 2;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       *系统消息生效 系统功能码
       * </pre>
       *
       * <code>int32 code = 2;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *系统消息生效 系统功能码
       * </pre>
       *
       * <code>int32 code = 2;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private Object fromId_ = "";
      /**
       * <code>string fromId = 3;</code>
       */
      public String getFromId() {
        Object ref = fromId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fromId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string fromId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFromIdBytes() {
        Object ref = fromId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fromId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fromId = 3;</code>
       */
      public Builder setFromId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fromId = 3;</code>
       */
      public Builder clearFromId() {
        
        fromId_ = getDefaultInstance().getFromId();
        onChanged();
        return this;
      }
      /**
       * <code>string fromId = 3;</code>
       */
      public Builder setFromIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromId_ = value;
        onChanged();
        return this;
      }

      private Object toId_ = "";
      /**
       * <code>string toId = 4;</code>
       */
      public String getToId() {
        Object ref = toId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          toId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string toId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getToIdBytes() {
        Object ref = toId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          toId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string toId = 4;</code>
       */
      public Builder setToId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string toId = 4;</code>
       */
      public Builder clearToId() {
        
        toId_ = getDefaultInstance().getToId();
        onChanged();
        return this;
      }
      /**
       * <code>string toId = 4;</code>
       */
      public Builder setToIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toId_ = value;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 5;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 5;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 5;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 5;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 5;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private long sendTime_ ;
      /**
       * <code>int64 sendTime = 6;</code>
       */
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <code>int64 sendTime = 6;</code>
       */
      public Builder setSendTime(long value) {
        
        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sendTime = 6;</code>
       */
      public Builder clearSendTime() {
        
        sendTime_ = 0L;
        onChanged();
        return this;
      }

      private int messageType_ ;
      /**
       * <pre>
       *1：系统消息  2：普通消息
       * </pre>
       *
       * <code>int32 messageType = 7;</code>
       */
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <pre>
       *1：系统消息  2：普通消息
       * </pre>
       *
       * <code>int32 messageType = 7;</code>
       */
      public Builder setMessageType(int value) {
        
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1：系统消息  2：普通消息
       * </pre>
       *
       * <code>int32 messageType = 7;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private int messageCategory_ ;
      /**
       * <pre>
       *消息类别 1 普通文本 2 文件
       * </pre>
       *
       * <code>int32 messageCategory = 8;</code>
       */
      public int getMessageCategory() {
        return messageCategory_;
      }
      /**
       * <pre>
       *消息类别 1 普通文本 2 文件
       * </pre>
       *
       * <code>int32 messageCategory = 8;</code>
       */
      public Builder setMessageCategory(int value) {
        
        messageCategory_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类别 1 普通文本 2 文件
       * </pre>
       *
       * <code>int32 messageCategory = 8;</code>
       */
      public Builder clearMessageCategory() {
        
        messageCategory_ = 0;
        onChanged();
        return this;
      }

      private int chatType_ ;
      /**
       * <pre>
       *聊天类型 1.群聊 2.私聊 3.消息推送
       * </pre>
       *
       * <code>int32 chatType = 9;</code>
       */
      public int getChatType() {
        return chatType_;
      }
      /**
       * <pre>
       *聊天类型 1.群聊 2.私聊 3.消息推送
       * </pre>
       *
       * <code>int32 chatType = 9;</code>
       */
      public Builder setChatType(int value) {
        
        chatType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *聊天类型 1.群聊 2.私聊 3.消息推送
       * </pre>
       *
       * <code>int32 chatType = 9;</code>
       */
      public Builder clearChatType() {
        
        chatType_ = 0;
        onChanged();
        return this;
      }

      private int terminalType_ ;
      /**
       * <pre>
       *终端类型
       * </pre>
       *
       * <code>int32 terminalType = 10;</code>
       */
      public int getTerminalType() {
        return terminalType_;
      }
      /**
       * <pre>
       *终端类型
       * </pre>
       *
       * <code>int32 terminalType = 10;</code>
       */
      public Builder setTerminalType(int value) {
        
        terminalType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *终端类型
       * </pre>
       *
       * <code>int32 terminalType = 10;</code>
       */
      public Builder clearTerminalType() {
        
        terminalType_ = 0;
        onChanged();
        return this;
      }

      private Object protocol_ = "";
      /**
       * <pre>
       *协议
       * </pre>
       *
       * <code>string protocol = 11;</code>
       */
      public String getProtocol() {
        Object ref = protocol_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          protocol_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *协议
       * </pre>
       *
       * <code>string protocol = 11;</code>
       */
      public com.google.protobuf.ByteString
          getProtocolBytes() {
        Object ref = protocol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          protocol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *协议
       * </pre>
       *
       * <code>string protocol = 11;</code>
       */
      public Builder setProtocol(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        protocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *协议
       * </pre>
       *
       * <code>string protocol = 11;</code>
       */
      public Builder clearProtocol() {
        
        protocol_ = getDefaultInstance().getProtocol();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *协议
       * </pre>
       *
       * <code>string protocol = 11;</code>
       */
      public Builder setProtocolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        protocol_ = value;
        onChanged();
        return this;
      }

      private Object token_ = "";
      /**
       * <code>string token = 12;</code>
       */
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string token = 12;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 12;</code>
       */
      public Builder setToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 12;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 12;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private Object data_ = "";
      /**
       * <pre>
       *其他属性
       * </pre>
       *
       * <code>string data = 13;</code>
       */
      public String getData() {
        Object ref = data_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *其他属性
       * </pre>
       *
       * <code>string data = 13;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *其他属性
       * </pre>
       *
       * <code>string data = 13;</code>
       */
      public Builder setData(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *其他属性
       * </pre>
       *
       * <code>string data = 13;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *其他属性
       * </pre>
       *
       * <code>string data = 13;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private MessageFile messageFile_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          MessageFile, MessageFile.Builder, MessageFileOrBuilder> messageFileBuilder_;
      /**
       * <code>.com.asm.zim.common.proto.MessageFile messageFile = 14;</code>
       */
      public boolean hasMessageFile() {
        return messageFileBuilder_ != null || messageFile_ != null;
      }
      /**
       * <code>.com.asm.zim.common.proto.MessageFile messageFile = 14;</code>
       */
      public MessageFile getMessageFile() {
        if (messageFileBuilder_ == null) {
          return messageFile_ == null ? MessageFile.getDefaultInstance() : messageFile_;
        } else {
          return messageFileBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.asm.zim.common.proto.MessageFile messageFile = 14;</code>
       */
      public Builder setMessageFile(MessageFile value) {
        if (messageFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          messageFile_ = value;
          onChanged();
        } else {
          messageFileBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.asm.zim.common.proto.MessageFile messageFile = 14;</code>
       */
      public Builder setMessageFile(
          MessageFile.Builder builderForValue) {
        if (messageFileBuilder_ == null) {
          messageFile_ = builderForValue.build();
          onChanged();
        } else {
          messageFileBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.asm.zim.common.proto.MessageFile messageFile = 14;</code>
       */
      public Builder mergeMessageFile(MessageFile value) {
        if (messageFileBuilder_ == null) {
          if (messageFile_ != null) {
            messageFile_ =
              MessageFile.newBuilder(messageFile_).mergeFrom(value).buildPartial();
          } else {
            messageFile_ = value;
          }
          onChanged();
        } else {
          messageFileBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.asm.zim.common.proto.MessageFile messageFile = 14;</code>
       */
      public Builder clearMessageFile() {
        if (messageFileBuilder_ == null) {
          messageFile_ = null;
          onChanged();
        } else {
          messageFile_ = null;
          messageFileBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.asm.zim.common.proto.MessageFile messageFile = 14;</code>
       */
      public MessageFile.Builder getMessageFileBuilder() {
        
        onChanged();
        return getMessageFileFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.asm.zim.common.proto.MessageFile messageFile = 14;</code>
       */
      public MessageFileOrBuilder getMessageFileOrBuilder() {
        if (messageFileBuilder_ != null) {
          return messageFileBuilder_.getMessageOrBuilder();
        } else {
          return messageFile_ == null ?
              MessageFile.getDefaultInstance() : messageFile_;
        }
      }
      /**
       * <code>.com.asm.zim.common.proto.MessageFile messageFile = 14;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          MessageFile, MessageFile.Builder, MessageFileOrBuilder>
          getMessageFileFieldBuilder() {
        if (messageFileBuilder_ == null) {
          messageFileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              MessageFile, MessageFile.Builder, MessageFileOrBuilder>(
                  getMessageFile(),
                  getParentForChildren(),
                  isClean());
          messageFile_ = null;
        }
        return messageFileBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.asm.zim.common.proto.Message)
    }

    // @@protoc_insertion_point(class_scope:com.asm.zim.common.proto.Message)
    private static final Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message();
    }

    public static Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @Override
    public Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_asm_zim_common_proto_MessageFile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_asm_zim_common_proto_MessageFile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_asm_zim_common_proto_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_asm_zim_common_proto_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022base_message.proto\022\030com.asm.zim.common" +
      ".proto\"}\n\013MessageFile\022\n\n\002id\030\001 \001(\t\022\021\n\tmes" +
      "sageId\030\002 \001(\t\022\020\n\010fileName\030\003 \001(\t\022\014\n\004size\030\004" +
      " \001(\003\022\016\n\006suffix\030\005 \001(\t\022\013\n\003url\030\006 \001(\t\022\022\n\ncre" +
      "ateTime\030\007 \001(\003\"\245\002\n\007Message\022\n\n\002id\030\001 \001(\t\022\014\n" +
      "\004code\030\002 \001(\005\022\016\n\006fromId\030\003 \001(\t\022\014\n\004toId\030\004 \001(" +
      "\t\022\017\n\007content\030\005 \001(\t\022\020\n\010sendTime\030\006 \001(\003\022\023\n\013" +
      "messageType\030\007 \001(\005\022\027\n\017messageCategory\030\010 \001" +
      "(\005\022\020\n\010chatType\030\t \001(\005\022\024\n\014terminalType\030\n \001" +
      "(\005\022\020\n\010protocol\030\013 \001(\t\022\r\n\005token\030\014 \001(\t\022\014\n\004d" +
      "ata\030\r \001(\t\022:\n\013messageFile\030\016 \001(\0132%.com.asm" +
      ".zim.common.proto.MessageFileb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_asm_zim_common_proto_MessageFile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_asm_zim_common_proto_MessageFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_asm_zim_common_proto_MessageFile_descriptor,
        new String[] { "Id", "MessageId", "FileName", "Size", "Suffix", "Url", "CreateTime", });
    internal_static_com_asm_zim_common_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_asm_zim_common_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_asm_zim_common_proto_Message_descriptor,
        new String[] { "Id", "Code", "FromId", "ToId", "Content", "SendTime", "MessageType", "MessageCategory", "ChatType", "TerminalType", "Protocol", "Token", "Data", "MessageFile", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
